nodeLinker: node-modules

packageExtensions:
  "@ai-sdk/react@*":
    peerDependencies:
      zod: "*"
  "@assistant-ui/react-ai-sdk@*":
    peerDependencies:
      zod: "*"
  "@assistant-ui/react-markdown@*":
    peerDependencies:
      react-dom: "*"
